# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_caution(object):
    def setupUi(self, caution):
        caution.setObjectName("caution")
        caution.resize(422, 253)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Bao/Downloads/bug_danger_data_internet_malware_security_virus_icon_127084.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        caution.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(caution)
        self.frame.setGeometry(QtCore.QRect(10, 10, 401, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.warntext = QtWidgets.QLabel(self.frame)
        self.warntext.setGeometry(QtCore.QRect(110, 60, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.warntext.setFont(font)
        self.warntext.setObjectName("warntext")

        self.retranslateUi(caution)
        QtCore.QMetaObject.connectSlotsByName(caution)

    def retranslateUi(self, caution):
        _translate = QtCore.QCoreApplication.translate
        caution.setWindowTitle(_translate("caution", "caution"))
        self.warntext.setText(_translate("caution", "No images selected"))

    def resettext(self,a0 = None):
        if a0 == 100:
            self.warntext.setText("No images selected")
        elif a0 == 200:
            self.warntext.setText("No file save path")
        elif a0 == 300:
            self.warntext.setText("Path does not exist")
        elif a0 == 400:
            self.warntext.setText("The number of uses: 0")


        self.warntext.update()

